version: '3.4'

services:
  whatsapppython:
    image: whatsapppython
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
